# SPDX-License-Identifier: GPL-2.0-or-later


# ##### BEGIN AUTOGENERATED I18N SECTION #####
# NOTE: You can safely move around this auto-generated block (with the begin/end markers!),
#       and edit the translations by hand.
#       Just carefully respect the format of the tuple!

# Tuple of tuples:
# ((msgctxt, msgid), (sources, gen_comments), (lang, translation, (is_fuzzy, comments)), ...)
translations_tuple = (
    (
        ("*", ""),
        ((), ()),
        (
            "zh_HANS",
            "Project-Id-Version: Playblast 1.0.0 (0)\nReport-Msgid-Bugs-To: \nPOT-Creation-Date: 2025-10-27 02:58+0800\nPO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\nLast-Translator: FULL NAME <EMAIL@ADDRESS>\nLanguage-Team: LANGUAGE <LL@li.org>\nLanguage: __POT__\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit",
            (False, ("FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.",)),
        ),
    ),
    (
        ("Operator", "Export Settings"),
        (
            (
                "bpy.types.PLAYBLAST_OT_export_settings",
                "bpy.types.PLAYBLAST_OT_export_settings",
            ),
            (),
        ),
        ("zh_HANS", "导出设置", (False, ())),
    ),
    (
        ("Operator", "Import Settings"),
        (
            (
                "bpy.types.PLAYBLAST_OT_import_settings",
                "bpy.types.PLAYBLAST_OT_import_settings",
            ),
            (),
        ),
        ("zh_HANS", "导入设置", (False, ())),
    ),
    (
        ("Operator", "Run Playblast"),
        (("bpy.types.PLAYBLAST_OT_run", "bpy.types.PLAYBLAST_OT_run"), ()),
        ("zh_HANS", "运行拍屏", (False, ())),
    ),
    (
        ("Operator", "Save As Default"),
        (
            (
                "bpy.types.PLAYBLAST_OT_save_as_default",
                "bpy.types.PLAYBLAST_OT_save_as_default",
            ),
            (),
        ),
        ("zh_HANS", "保存为默认", (False, ())),
    ),
    (
        ("*", "Export current playblast settings to a file"),
        (("bpy.types.PLAYBLAST_OT_export_settings",), ()),
        ("zh_HANS", "将当前拍屏设置导出到文件", (False, ())),
    ),
    (
        ("*", "Import playblast settings from a file"),
        (("bpy.types.PLAYBLAST_OT_import_settings",), ()),
        ("zh_HANS", "从文件导入拍屏设置", (False, ())),
    ),
    (
        (
            "*",
            "Create a playblast video of the current scene.\nPlease ensure you have an active camera and ffmpeg is installed in your system.",
        ),
        (("bpy.types.PLAYBLAST_OT_run",), ()),
        (
            "zh_HANS",
            "为当前场景创建拍屏视频。\n请确保场景有激活的相机且系统已安装 ffmpeg。",
            (False, ()),
        ),
    ),
    (
        (
            "*",
            "Save the current playblast settings as default, then your new blender file will use these playblast settings as default.",
        ),
        (("bpy.types.PLAYBLAST_OT_save_as_default",), ()),
        (
            "zh_HANS",
            "将当前拍屏设置保存为默认，新创建的 Blender 文件将使用这些默认设置。",
            (False, ()),
        ),
    ),
    (
        ("*", "Text to display in the bottom center"),
        (("bpy.types.BurnInProperties.bottom_center",), ()),
        ("zh_HANS", "在底部中央显示的文字", (False, ())),
    ),
    (
        ("*", "Text to display in the bottom left corner"),
        (("bpy.types.BurnInProperties.bottom_left",), ()),
        ("zh_HANS", "在左下角显示的文字", (False, ())),
    ),
    (
        ("*", "Text to display in the bottom right corner"),
        (("bpy.types.BurnInProperties.bottom_right",), ()),
        ("zh_HANS", "在右下角显示的文字", (False, ())),
    ),
    (
        ("*", "Color of the burn-in text"),
        (("bpy.types.BurnInProperties.color",), ()),
        ("zh_HANS", "叠加文字颜色", (False, ())),
    ),
    (
        ("*", "Enable Burn-In Data"),
        (("bpy.types.BurnInProperties.enable",), ()),
        ("zh_HANS", "启用叠加信息", (False, ())),
    ),
    (
        (
            "*",
            "Enable burn-in text overlay on the playblast, if not specified, use blender default font",
        ),
        (("bpy.types.BurnInProperties.enable",), ()),
        ("zh_HANS", "在拍屏上启用叠加文字", (False, ())),
    ),
    (
        ("*", "Font Family"),
        (("bpy.types.BurnInProperties.font_family",), ()),
        ("zh_HANS", "字体", (False, ())),
    ),
    (
        ("*", "Font family for the burn-in text"),
        (("bpy.types.BurnInProperties.font_family",), ()),
        ("zh_HANS", "叠写文字的字体", (False, ())),
    ),
    (
        ("*", "Size of the burn-in text font"),
        (("bpy.types.BurnInProperties.font_size",), ()),
        ("zh_HANS", "叠写文字的字体大小", (False, ())),
    ),
    (
        ("*", "Text margin from the edges of the viewport"),
        (("bpy.types.BurnInProperties.margin",), ()),
        ("zh_HANS", "文本与视口边缘的间距", (False, ())),
    ),
    (
        ("*", "Preview in Viewport"),
        (("bpy.types.BurnInProperties.preview",), ()),
        ("zh_HANS", "在视口中预览", (False, ())),
    ),
    (
        (
            "*",
            "Preview the burn-in text in the 3D viewport\nYou need to be in Camera view to see it",
        ),
        (("bpy.types.BurnInProperties.preview",), ()),
        ("zh_HANS", "在 3D 视口中预览叠写文字\n需要处于相机视图才能看到", (False, ())),
    ),
    (
        ("*", "Text to display in the top center"),
        (("bpy.types.BurnInProperties.top_center",), ()),
        ("zh_HANS", "在顶部中央显示的文字", (False, ())),
    ),
    (
        ("*", "Text to display in the top left corner"),
        (("bpy.types.BurnInProperties.top_left",), ()),
        ("zh_HANS", "在左上角显示的文字", (False, ())),
    ),
    (
        ("*", "Text to display in the top right corner"),
        (("bpy.types.BurnInProperties.top_right",), ()),
        ("zh_HANS", "在右上角显示的文字", (False, ())),
    ),
    (
        (
            "*",
            "Directory to save playblast file.\nIf not specified, use current blend file directory.\nOr use system temp directory if blend file is not saved.",
        ),
        (("bpy.types.FileProperties.directory",), ()),
        (
            "zh_HANS",
            "保存拍屏文件的目录。\n若未指定，使用当前 .blend 文件所在目录；若 .blend 未保存，则使用系统临时目录。",
            (False, ()),
        ),
    ),
    (
        ("*", "File extension for playblast"),
        (("bpy.types.FileProperties.extension",), ()),
        ("zh_HANS", "拍屏文件的扩展名", (False, ())),
    ),
    (
        ("*", "MP4 format"),
        (("bpy.types.FileProperties.extension:'.mp4'",), ()),
        ("zh_HANS", "MP4 格式", (False, ())),
    ),
    (
        ("*", "AVI format"),
        (("bpy.types.FileProperties.extension:'.avi'",), ()),
        ("zh_HANS", "AVI 格式", (False, ())),
    ),
    (
        ("*", "MOV format"),
        (("bpy.types.FileProperties.extension:'.mov'",), ()),
        ("zh_HANS", "MOV 格式", (False, ())),
    ),
    (
        (
            "*",
            "Read-only properties.\nJoin all parts to get the full path of the playblast file.",
        ),
        (("bpy.types.FileProperties.full_path",), ()),
        (
            "zh_HANS",
            "只读属性。\n将所有部分拼接以获取拍屏文件的完整路径。",
            (False, ()),
        ),
    ),
    (
        ("*", "Base name for playblast file"),
        (("bpy.types.FileProperties.name",), ()),
        ("zh_HANS", "拍屏文件的名称", (False, ())),
    ),
    (
        ("*", "Use Version"),
        (("bpy.types.FileProperties.use_version",), ()),
        ("zh_HANS", "使用版本", (False, ())),
    ),
    (
        ("*", "Version number for the playblast file"),
        (("bpy.types.FileProperties.version",), ()),
        ("zh_HANS", "拍屏文件的版本号", (False, ())),
    ),
    (
        ("*", "Version String"),
        (("bpy.types.FileProperties.version_str",), ()),
        ("zh_HANS", "版本字符串", (False, ())),
    ),
    (
        (
            "*",
            "Read-only properties.\nGet version string from the version number.If version is 1, return v001.Else return empty string.",
        ),
        (("bpy.types.FileProperties.version_str",), ()),
        (
            "zh_HANS",
            "只读属性。\n从版本号获取版本字符串。如果版本为 1，返回 v001；否则返回空字符串。",
            (False, ()),
        ),
    ),
    (
        ("*", "First Load"),
        (("bpy.types.PlayblastProperties.first_load",), ()),
        ("zh_HANS", "首次加载", (False, ())),
    ),
    (
        (
            "*",
            "Internal property.\nIndicate if this is the first time loading the playblast settings.\nIf true, load default settings from the saved json file.\nIt will be set and persisted to false after the first load.",
        ),
        (("bpy.types.PlayblastProperties.first_load",), ()),
        (
            "zh_HANS",
            "内部属性。\n指示是否为首次加载拍屏设置。\n如果为真，则从已保存的 json 文件加载默认设置。\n首次加载后该属性将被设置并持久化为 false。",
            (False, ()),
        ),
    ),
    (
        ("*", "Video codec for playblast"),
        (("bpy.types.VideoProperties.codec",), ()),
        ("zh_HANS", "拍屏的视频编码器", (False, ())),
    ),
    (
        ("*", "H.264 codec"),
        (("bpy.types.VideoProperties.codec:'libx264'",), ()),
        ("zh_HANS", "H.264 编码", (False, ())),
    ),
    (
        ("*", "H.265"),
        (("bpy.types.VideoProperties.codec:'libx265'",), ()),
        ("zh_HANS", "H.265", (False, ())),
    ),
    (
        ("*", "HEVC codec"),
        (("bpy.types.VideoProperties.codec:'libx265'",), ()),
        ("zh_HANS", "HEVC 编码", (False, ())),
    ),
    (
        ("*", "MPEG-4 codec"),
        (("bpy.types.VideoProperties.codec:'mpeg4'",), ()),
        ("zh_HANS", "MPEG-4 编码", (False, ())),
    ),
    (
        ("*", "AV1 codec"),
        (("bpy.types.VideoProperties.codec:'libsvtav1'",), ()),
        ("zh_HANS", "AV1 编码", (False, ())),
    ),
    (
        ("*", "End frame for the playblast"),
        (("bpy.types.VideoProperties.frame_end",), ()),
        ("zh_HANS", "拍屏的结束帧", (False, ())),
    ),
    (
        ("*", "Start frame for the playblast"),
        (("bpy.types.VideoProperties.frame_start",), ()),
        ("zh_HANS", "拍屏的起始帧", (False, ())),
    ),
    (
        ("*", "Include Audio"),
        (("bpy.types.VideoProperties.include_audio",), ()),
        ("zh_HANS", "包含音频", (False, ())),
    ),
    (
        ("*", "Include audio in the playblast video"),
        (("bpy.types.VideoProperties.include_audio",), ()),
        ("zh_HANS", "在拍屏视频中包含音频", (False, ())),
    ),
    (
        ("*", "Scale factor for the playblast resolution"),
        (("bpy.types.VideoProperties.scale",), ()),
        ("zh_HANS", "拍屏分辨率的缩放因子", (False, ())),
    ),
    (
        (
            "*",
            "Use specific frame range for the playblast instead of the entire scene frame range",
        ),
        (("bpy.types.VideoProperties.use_frame_range",), ()),
        ("zh_HANS", "使用指定的帧范围进行拍屏而非整个场景的帧范围", (False, ())),
    ),
    (
        ("*", "Playblast started, press ESC to cancel it"),
        (("extensions/vscode_development/playblast/operators.py:75",), ()),
        ("zh_HANS", "拍屏已开始，按 ESC 可取消", (False, ())),
    ),
    (
        (
            "*",
            "Default playblast settings saved. New blender files will use these settings.",
        ),
        (("extensions/vscode_development/playblast/operators.py:398",), ()),
        (
            "zh_HANS",
            "默认拍屏设置已保存。新建的 Blender 文件将使用这些设置。",
            (False, ()),
        ),
    ),
    (
        ("*", "FFmpeg is not installed or not found in PATH."),
        (("extensions/vscode_development/playblast/operators.py:34",), ()),
        ("zh_HANS", "未安装 FFmpeg 或未在 PATH 中找到。", (False, ())),
    ),
    (
        ("*", "Playblast canceled"),
        (("extensions/vscode_development/playblast/operators.py:104",), ()),
        ("zh_HANS", "拍屏已取消", (False, ())),
    ),
    (
        ("*", "Failed to build video with ffmpeg."),
        (("extensions/vscode_development/playblast/operators.py:381",), ()),
        ("zh_HANS", "使用 ffmpeg 生成视频失败。", (False, ())),
    ),
    (
        ("*", "Playblast completed, saved to , opening file."),
        (("extensions/vscode_development/playblast/operators.py:384",), ()),
        ("zh_HANS", "拍屏完成，已保存至，正在打开文件。", (False, ())),
    ),
    (
        ("*", "Failed to set up running settings: "),
        (("extensions/vscode_development/playblast/operators.py:71",), ()),
        ("zh_HANS", "设置运行配置失败：", (False, ())),
    ),
    (
        ("Operator", "Run"),
        (("extensions/vscode_development/playblast/panels.py:20",), ()),
        ("zh_HANS", "运行", (False, ())),
    ),
    (
        ("*", "Video Codec"),
        (("extensions/vscode_development/playblast/panels.py:25",), ()),
        ("zh_HANS", "视频编码", (False, ())),
    ),
    (
        ("*", "Resolution Scale"),
        (("extensions/vscode_development/playblast/panels.py:26",), ()),
        ("zh_HANS", "分辨率缩放", (False, ())),
    ),
    (
        ("*", "Override Range"),
        (("extensions/vscode_development/playblast/panels.py:28",), ()),
        ("zh_HANS", "覆盖帧范围", (False, ())),
    ),
    (
        ("*", "Start"),
        (("extensions/vscode_development/playblast/panels.py:32",), ()),
        ("zh_HANS", "开始", (False, ())),
    ),
    (
        ("*", "End"),
        (("extensions/vscode_development/playblast/panels.py:33",), ()),
        ("zh_HANS", "结束", (False, ())),
    ),
    (
        ("*", "Default to current blend file directory"),
        (("extensions/vscode_development/playblast/panels.py:57",), ()),
        ("zh_HANS", "默认使用当前 .blend 文件目录", (False, ())),
    ),
    (
        ("*", "Version"),
        (("extensions/vscode_development/playblast/panels.py:61",), ()),
        ("zh_HANS", "版本", (False, ())),
    ),
    (
        ("*", "Default to Blender Font"),
        (("extensions/vscode_development/playblast/panels.py:103",), ()),
        ("zh_HANS", "默认使用 Blender 字体", (False, ())),
    ),
    (
        (
            "*",
            "Use curly braces {} to denote variables in text, for example {datetime} for the current time.",
        ),
        (("extensions/vscode_development/playblast/panels.py:128",), ()),
        (
            "zh_HANS",
            "在文本中使用花括号 {} 表示变量，例如 {datetime} 表示当前时间。",
            (False, ()),
        ),
    ),
    (
        ("*", "The following variables are currently available:"),
        (("extensions/vscode_development/playblast/panels.py:130",), ()),
        ("zh_HANS", "当前可用的变量如下：", (False, ())),
    ),
    (
        ("Operator", "Save as Default"),
        (("extensions/vscode_development/playblast/panels.py:154",), ()),
        ("zh_HANS", "保存为默认", (False, ())),
    ),
    (
        ("Operator", "Import"),
        (("extensions/vscode_development/playblast/panels.py:158",), ()),
        ("zh_HANS", "导入", (False, ())),
    ),
    (
        ("Operator", "Export"),
        (("extensions/vscode_development/playblast/panels.py:159",), ()),
        ("zh_HANS", "导出", (False, ())),
    ),
    (
        ("*", "{}"),
        (("extensions/vscode_development/playblast/panels.py:134",), ()),
        ("zh_HANS", "", (False, ())),
    ),
    (
        ("*", "Playblast"),
        (("Add-on Playblast info: name",), ()),
        ("zh_HANS", "拍屏", (False, ())),
    ),
    (
        ("*", "Blender playblast tool similarly to Maya"),
        (("Add-on Playblast info: description",), ()),
        ("zh_HANS", "类似于 Maya 的 Blender 拍屏工具", (False, ())),
    ),
    (
        ("*", "Current date and time"),
        ((), ()),
        ("zh_HANS", "当前日期和时间", (False, ())),
    ),
    (
        ("*", "Playblast width in pixels"),
        ((), ()),
        ("zh_HANS", "拍屏宽度（像素）", (False, ())),
    ),
    (
        ("*", "Playblast height in pixels"),
        ((), ()),
        ("zh_HANS", "拍屏高度（像素）", (False, ())),
    ),
    (
        ("*", "Name of the output file without extension"),
        ((), ()),
        ("zh_HANS", "输出文件名（不含扩展名）", (False, ())),
    ),
    (
        ("*", "Version string of the output file"),
        ((), ()),
        ("zh_HANS", "输出文件的版本字符串", (False, ())),
    ),
    (
        ("*", "File extension of the output file"),
        ((), ()),
        ("zh_HANS", "输出文件的扩展名", (False, ())),
    ),
    (
        ("*", "Full name of the output file with extension"),
        ((), ()),
        ("zh_HANS", "包含扩展名的完整输出文件名", (False, ())),
    ),
    (
        ("*", "Current frame number"),
        ((), ()),
        ("zh_HANS", "当前帧数", (False, ())),
    ),
    (
        ("*", "Start frame of the scene"),
        ((), ()),
        ("zh_HANS", "拍屏起始帧", (False, ())),
    ),
    (
        ("*", "End frame of the scene"),
        ((), ()),
        ("zh_HANS", "拍屏结束帧", (False, ())),
    ),
    (
        ("*", "Frame rate of the scene"),
        ((), ()),
        ("zh_HANS", "拍屏帧率", (False, ())),
    ),
    (
        ("*", "Name of the active camera"),
        ((), ()),
        ("zh_HANS", "激活相机的名称", (False, ())),
    ),
    (
        ("*", "Focal length of the active camera in mm"),
        ((), ()),
        ("zh_HANS", "激活相机的焦距（毫米）", (False, ())),
    ),
)

translations_dict = {}
for msg in translations_tuple:
    key = msg[0]
    for lang, trans, (is_fuzzy, comments) in msg[2:]:
        if trans and not is_fuzzy:
            translations_dict.setdefault(lang, {})[key] = trans

# ##### END AUTOGENERATED I18N SECTION #####
